[build]
  functions = "functions"
[dev]
  command = "yarn start" # Command to start your dev server
  targetPort = 8000 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "dist"
  autoLaunch = true 
  functionsPort = 34567
	functions = "./functions"
[[redirects]]
  from = "api/*"
  to = ".netlify/functions/:splat"
  status = 200